### ISSUE TITLE
panic: setting PGLOCALEDIR not supported

### ISSUE THREAD

**Issue by heri16** [amacneil/dbmate#177]
I got this error on Arch Linux after `npm i dbmate`:

dbmate-linux-musl-amd64

```
$ dbmate create
Creating: postgres
panic: setting PGLOCALEDIR not supported

goroutine 1 [running]:
github.com/lib/pq.parseEnviron.func2(...)
	/go/pkg/mod/github.com/lib/pq@v1.2.0/conn.go:1848
github.com/lib/pq.parseEnviron(0xc000087000, 0x80, 0x80, 0xc00006d7a0)
	/go/pkg/mod/github.com/lib/pq@v1.2.0/conn.go:1901 +0x147f
github.com/lib/pq.NewConnector(0xc00008a680, 0x69, 0xc00010d2e8, 0xc000090d20, 0xc000090d20)
	/go/pkg/mod/github.com/lib/pq@v1.2.0/connector.go:56 +0x13e
github.com/lib/pq.DialOpen(0x860960, 0xc000090d20, 0xc00008a680, 0x69, 0x20300000000000, 0x7f5bd8bcafff, 0x7f5bdabe86c0, 0xc001c0001442c0)
	/go/pkg/mod/github.com/lib/pq@v1.2.0/conn.go:271 +0x39
github.com/lib/pq.Open(...)
	/go/pkg/mod/github.com/lib/pq@v1.2.0/conn.go:266
github.com/lib/pq.(*Driver).Open(0xac6bb0, 0xc00008a680, 0x69, 0x0, 0x0, 0x7f5bdabe8600, 0x0)
	/go/pkg/mod/github.com/lib/pq@v1.2.0/conn.go:48 +0x9a
database/sql.dsnConnector.Connect(...)
	/usr/local/go/src/database/sql/sql.go:688
database/sql.(*DB).conn(0xc000148000, 0x863820, 0xc00008c010, 0x1, 0xc00008cc40, 0xa, 0x10000000000000a)
	/usr/local/go/src/database/sql/sql.go:1228 +0x201
database/sql.(*DB).exec(0xc000148000, 0x863820, 0xc00008c010, 0xc0000a0a20, 0x1a, 0x0, 0x0, 0x0, 0x4cfd01, 0xc00006f040, ...)
	/usr/local/go/src/database/sql/sql.go:1495 +0x66
database/sql.(*DB).ExecContext(0xc000148000, 0x863820, 0xc00008c010, 0xc0000a0a20, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/database/sql/sql.go:1477 +0xde
database/sql.(*DB).Exec(...)
	/usr/local/go/src/database/sql/sql.go:1491
github.com/amacneil/dbmate/pkg/dbmate.PostgresDriver.CreateDatabase(0xc0000d0400, 0x0, 0x0)
	/src/pkg/dbmate/postgres.go:46 +0x257
github.com/amacneil/dbmate/pkg/dbmate.(*DB).Create(0xc000067080, 0x7e5231, 0xf)
	/src/pkg/dbmate/db.go:116 +0x70
main.NewApp.func3(0xc000067080, 0xc0000e02c0, 0xb, 0x7e5231)
	/src/main.go:75 +0x2b
main.action.func1(0xc0000e02c0, 0x0, 0xc00006bb40)
	/src/main.go:142 +0x1c5
github.com/urfave/cli.HandleAction(0x77e840, 0xc00006b730, 0xc0000e02c0, 0xc0000e02c0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:521 +0xf1
github.com/urfave/cli.Command.Run(0x7dfcf7, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7e52d6, 0xf, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.1/command.go:174 +0x51c
github.com/urfave/cli.(*App).Run(0xc00013e000, 0xc000082020, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.1/app.go:276 +0x718
main.main()
	/src/main.go:18 +0x54
```

### .env
```
DATABASE_URL="postgres://postgres:postgres@127.0.0.1:5432/postgres?search_path=app_public,app_private,app_hidden,public"
DBMATE_MIGRATIONS_DIR=./migrations
DBMATE_SCHEMA_FILE=./schema.sql
```

**Comment by heri16** [comment]
**Solution:**
```bash
unset PGLOCALEDIR
```

**Comment by amacneil** [comment]
What behavior were you expecting?
